# https://hub.docker.com/r/itsthenetwork/nfs-server-alpine/
# https://container42.com/2014/03/29/docker-quicktip-4-remote-volumes/
# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-volumes-example-nfs-persistent-volume.html
# https://hub.docker.com/r/erichough/nfs-server/
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  selector:
    role: nfs
  ports:
    # Open the ports required by the NFS server
    # Port 2049 for TCP
    - name: tcp-2049
      port: 2049
      protocol: TCP