apiVersion: v1
kind: Service
metadata:
  name: halyard-echo2
  labels:
    app: halyard
    component: echo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: halyard
    component: echo