---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halyard-backend-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halyard-backend-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi