name: package
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!startsWith(github.event.commits[0].message, 'chore(release):')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TRAXITT_NARAYAN_PAT }}
          submodules: true
      - name: Build on nodejs 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # The functional ui tests require xvfb for the headless browser.
      - run: sudo apt-get install xvfb
      - run: export DISPLAY=':99.0'
      - run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      # the yarn commands need to be in sync with the Dockerfile. (minus the yarn del)
      - run: yarn install --unsafe-perm
      - run: yarn build
      # Unit Tests
      - run: yarn unit-tests
      - run: xvfb-run --auto-servernum yarn functional-ui-tests
      # Functional tests: Needs a database, keep run and env statements together!
      - run: docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.4.0
      - run: yarn functional-tests
        env:
          HUB_MONGODB_TEST_URL: mongodb://127.0.0.1:27017/traxitt-hub-test
          STRIPE_SECRET_TOKEN: ${{ secrets.TEST_STRIPE_SECRET_TOKEN }}
      # Integration tests: Needs a database (started before the functional tests. Keep run and env statements together!
      - run: yarn integration-tests
        env:
          HUB_MONGODB_TEST_URL: mongodb://127.0.0.1:27017/traxitt-hub-test
          STRIPE_SECRET_TOKEN: ${{ secrets.TEST_STRIPE_SECRET_TOKEN }}
      - name: Log in to docker registry
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push dragon images
        run: |
          export USER=$(echo $GITHUB_SHA | cut -c 1-7)
          export C6O_VERSION=$USER

          docker build -t c6oio/node-monorepo:$USER .
          docker-compose build
          docker-compose push

          export USER=dragon
          docker build -t c6oio/node-monorepo:$USER .
          docker-compose build
          docker-compose push
      - name: Deploy dragon to develop.codezero.io
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_DEVELOP_KEY }}
        run: |
          echo "$GCLOUD_KEY" | base64 --decode > ${HOME}/gcloud.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
          gcloud container clusters get-credentials hub --zone us-central1-c --project traxitt-development
          export TAG=$(echo $GITHUB_SHA | cut -c 1-7)
          kubectl -n c6o-hub set image deploy/hub-server hub-server=c6oio/hub-server:$TAG
          kubectl -n c6o-hub set image deploy/hub-web hub-web=c6oio/hub-web:$TAG
          kubectl -n c6o-hub set image deploy/hub-dockyard hub-dockyard=c6oio/hub-dockyard:$TAG