name: package
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!startsWith(github.event.commits[0].message, 'chore(release):')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Build on nodejs 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Add pnpm
      - run: yarn global add pnpm
      - run: git rev-parse --verify HEAD

      # Install and Build
      - run: yarn install --unsafe-perm
      - run: yarn build

      # Package
      - name: Log in to docker registry
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push dragon images
        run: |
          export USER=$(echo $GITHUB_SHA | cut -c 1-7)
          export C6O_VERSION=$USER

          docker build -t robblovell/halyard-backend:$USER .
          docker-compose build
          docker-compose push

      - name: Deploy darkly
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_DEVELOP_KEY }}
        run: |
          echo "$GCLOUD_KEY" | base64 --decode > ${HOME}/gcloud.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
          gcloud container clusters get-credentials hub --zone us-central1-c --project traxitt-development
          export TAG=$(echo $GITHUB_SHA | cut -c 1-7)
          kubectl -n c6o-hub set image deploy/hub-server hub-server=c6oio/hub-server:$TAG
          kubectl -n c6o-hub set image deploy/hub-web hub-web=c6oio/hub-web:$TAG
          kubectl -n c6o-hub set image deploy/hub-dockyard hub-dockyard=c6oio/hub-dockyard:$TAG